name: Docker Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mandarin3d/mandarin3d-slicer:latest, mandarin3d/mandarin3d-slicer:${{ github.sha }}
    - name: Send JSON to API endpoint
      run: |
        curl -X PUT "https://dockerapi.raavai.com/control/redeploy" \
        -H "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"dc_name": "mandarin3d-slicer-api", "dc_ip": "192.168.10.120", "dc_port": 5030, "dc_image": "mandarin3d/mandarin3d-slicer"}'
